name: eps
version: 0.1.0.0
github: "rl-king/eps"
license: BSD3
author: "Ruben Lie King"
maintainer: "hello@rubenlieking.com"
copyright: "2018 Ruben Lie King"


extra-source-files:
  - README.md


description: Please see the README on GitHub at <https://github.com/rl-king/eps#readme>


dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - full-text-search
  - http-client
  - http-client-tls
  - snap-core
  - snap-server
  - text


library:
  source-dirs: src
  exposed-modules:
    Main


executables:
  eps:
    main: Main.hs
    source-dirs: src
    dependencies:
      - eps


tests:
  eps-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - eps
